### ISSUE TITLE
GPU Out of Memory

### ISSUE THREAD

**Issue by RichardHGL** [TaoMiner/joint-kg-recommender#1]
It seems this framework will go out of memory for Knowledge representation when processing ml-1m. My GPU memory is about 12GB.

> THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory
> Traceback (most recent call last):
>   File "run_knowledge_representation.py", line 13, in <module>
>     knowledge_representation.run(only_forward=FLAGS.eval_only_mode)
>   File "/home/xx/tools/joint-kg-recommender/jTransUP/models/knowledge_representation.py", line 308, in run
>     is_report=False)
>   File "/home/xx/tools/joint-kg-recommender/jTransUP/models/knowledge_representation.py", line 146, in train_loop
>     performances.append( evaluate(FLAGS, model, entity_total, relation_total, eval_data[0], eval_data[1], eval_data[4], eval_data[5], eval_head_dicts, eval_tail_dicts, logger, eval_descending=False, is_report=is_report))
>   File "/home/xx/tools/joint-kg-recommender/jTransUP/models/knowledge_representation.py", line 60, in evaluate
>     scores = model.evaluateTail(h_var, r_var)
>   File "/home/xx/tools/joint-kg-recommender/jTransUP/models/transE.py", line 104, in evaluateTail
>     score = torch.sum((c_t_expand-ent_expand) ** 2, 2)
> RuntimeError: cuda runtime error (2) : out of memory at /pytorch/torch/lib/THC/generic/THCStorage.cu:58

**Comment by TaoMiner** [comment]
did you try to shrink the batch size?

**Comment by RichardHGL** [comment]
I will try it, thanks!
