### ISSUE TITLE
A problem about KG dataset

### ISSUE THREAD

**Issue by RichardHGL** [TaoMiner/joint-kg-recommender#3]
It seems that the knowledge graph dataset has overlap between train.data and test.data.

Such as triple "6330	11326	10" occured in both dbbook2014 trainset and test set. Which may affect the experiment of KG completion.

Besides, the triples in every set has also some triples repeated. You should have a look at it.

**Comment by TaoMiner** [comment]
Thanks for the reminder. I will check it.
