### ISSUE TITLE
python module not find error

### ISSUE THREAD

**Issue by qqbaodaww** [TaoMiner/joint-kg-recommender#4]
When I run the code for jtransup model, I find that logger `No module named utils.misc`

And in the folder named jTransUP, there's ./models/jTransUP.py which would confuse the import behavior. I don't know if there's some setup missed...

Could you please help me with this question?

**Comment by TaoMiner** [comment]
I am not sure, but maybe you can add the root folder to the PATH?

**Comment by qqbaodaww** [comment]
Oh, thank you! I'd tried this and it turns out that there's some problem in the environment... And now it works well.
Anyway, many thanks! : )
